dist: trusty

language: go

env:
  - GO111MODULE=on
go:
  - 1.12.x
  - master
git:
  depth: 1
os:
  - linux
  - osx
sudo: false
install: true
before_script:
  - go install golang.org/x/tools/cmd/cover
  - go install github.com/mattn/goveralls
script:
  - go test -v -race -tags mock -covermode=atomic -coverprofile=coverage.out ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
matrix:
  include:
    - os: linux
      go: "1.12.x"
      cache:
        directories:
          - $HOME/.cache/go-build # Cache the binaries
          - $GOPATH/pkg/mod       # Cache the Go modules

    - os: linux
      go: "master"
      cache:
        directories:
          - $HOME/.cache/go-build # Cache the binaries
          - $GOPATH/pkg/mod       # Cache the Go modules

    - os: osx
      go: "1.12.x"
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod

    - os: osx
      go: "master"
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod
